### ISSUE TITLE
Add typings file?

### ISSUE THREAD

**Issue by andrewdavidcostello** [codesuki/superagent-intercept#2]
I was wondering if it would be possible to get typings added for this module.

This is what I added for now (may not be the best solution as new to typescript)

```
declare module 'superagent-intercept' {
	import * as request from 'superagent'

	export default function Intercept( req:( err:request.Response, res:request.Response ) => void ): () => {}
}
```

Thanks!

**Comment by codesuki** [comment]
I never used typescript! Therefore I am not sure where to add it.
Would you mind sending a pullreq? I'll merge it!
